name: build
on:
  push:
    branches:
      - master
      - release
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Spelling
        uses: UnicornGlobal/spellcheck-github-actions@master
